var lines = 
    [
        {
            "line": "Lucid",
            "description": "The concept for LUCID is to emphasise the contrast between solids and voids through different compositional designs. Whilst showing the striking difference between opaque and transparent fabrics, there is also a theme of layering, which is an idea that cannot be ignored when exploring the theme of transparency. By approaching layering opacity creatively, the looks of LUCID embody the idea of subtle reveal, conceal and gradation.",
            "team": "Nicole Lee-Park / Sophie Lee / Somin Shim"
        }, 
        {
            "line": "Lautus",
            "description": "Women’s wear is very versatile and consists of many different types of articles of clothing than can be mixed and matched. By deconstructing these different pieces the line aims to stray away from something mundane. Lautus accentuates the use of straps and buckles in the pieces, playing with its potential functionality or pure aesthetics.",
            "team": "Yoon Young Kim"
        }, 
        {
            "line": "Nautico",
            "description": " The goal of Nautico is to explore the forms that emerge, either beautiful or grotesque, when classic nautical garments are united with the natural forms of the ocean. This line imagines the process of making as one of growth — where these classic clothing of the sea has had it’s DNA spliced with that of the nature that so often surrounds them. It is as though the garb which man has used to explore the ocean have spent so much time in that place that it has begun to merge and blur with the biology around it.",
            "team": "David Perry"
        }, 
        {
            "line": "Grip",
            "description": "The goal of this line was to take common western, female, clothing items (black jumpsuit, flowy sheer skirt, crop top, etc.) and recreate them both with a combination of traditional clothing materials (fabric, buttons, zippers, thread) as well as tennis-related items (tennis balls, tennis ball fuzz, and purple Tourna grip tape). Some of the pieces in this line are close to outfits you would wear in day-to-day life, while others are less practical to wear outside of a fashion runway, but are equally as intriguing to look at. I chose to name this line “Grip” because many of the pieces incorporate tennis grip tape.",
            "team": "Charlotte Deiss"
        }, 
        {
            "line": "Re:born",
            "description": "Re:born is a collection that breathes new life into discarded fabrics obtained from local designers. Each piece explores the beauty, asymmetry, and uniqueness intrinsic to every scrap. With this line, my intention was to bring awareness to the overwhelming waste generated by the fashion industry, and what could have been. ( Special thanks to Dawn Surgest, Hannah Moon-EECM, Heather Jankosky-Uptown by Kiya Tomlin, and Tereneh Mosley.)",
            "team": "Xiaoying Meng"
        }, 
        {
            "line": "Fete",
            "description": "All throughout history, art movements have changed and shaped our Western society in enormous ways.  Many of the artists who contributed powerful pieces to these movements were women, however, and are all-too-often overlooked instead of celebrated.  “Fete” seeks to empower and celebrate these women and the important artistic work they contributed.  Each of our 8 looks is inspired by a different female artist’s work! Come take a trip through the past with us as we celebrate these talented women and the beautiful artwork they created!",
            "team": "Laura Reviere, Lily Cunicelli"
        }, 
        {
            "line": "Eden",
            "description": "The causes of environmental degradation stem from those who are ignorant and naive, but also from those who want to live an apathetic, comfortable life. We see natural wonders in parts of our world but with generations passing and habitats ceasing to exist we are losing what is left of this Eden. Our line represents the degradation of Earth’s natural environment thanks to man’s menacing takeover. After delving into the realms of coral bleaching, deforestation, glacial melting and oil spills, we compiled our research into nine design experimental garments.",
            "team": "Vincent Derienzo / Leah Kendrick / Tyng Peck"
        }, 
        {
            "line": "Synergy:Coexist",
            "description": "SYNERGY : COEXIST explores the juxtaposition between rigidity and flexibility to demonstrate the synergy created between the basic structure in human nature. This line examines the different degrees of how humans can be related to different organisms in nature and how each characteristics strive for survival in society. SYNERGY : COEXIST is inspired by the use of wood and the relationship between the skeletal framework and interweaving of skin.",
            "team": "Min Young Jeong / Christine Kim"
        }, 
        {
            "line": "Found",
            "description": "You’ve heard of trash. You’ve heard of fashion. Now get ready for 'trashion.' Today, humans are driven by the need for more. Our consumerist patterns leave us in a recurrent state of desire that prompts buying more and appreciating less. In turn, we are desensitized to the value of everything, both big and small. Momentarily taking a step back from this consumerist mentality, and observing these mundane objects in a new light, we begin to see true value in the items we take for granted. We can redefine the meaning of beauty and expand it past traditional means.",
            "team": "Ashley Burbano  / Jessa Westheimer"
        }, 
        {
            "line": "Opaque",
            "description": "Opaque is an exploration into the experience of living with a mental disorder. All three of us share personal experiences with the multiplex nature of these illnesses, and were inspired by society’s treatment of affected individuals. There is a constant and relentless social stigma around diagnosing and treating mental disorders that pushes individuals to hide these parts of themselves from the opinion and judgment of others. With this line, we draw a connection between this defensive behavior and the basic function of clothing (as protection from the elements and outside world).",
            "team": "Sophia Kim / Jaclyn Saik / Alice Fang"
        }, 
        {
            "line": "Alluminare",
            "description": "v. al.luː.miˈnaː.re (transitive) to add gold or silver to pigments in order to make the painting (usually a miniature) shine\n\nAlluminare seeks to explore how fashion can exist outside the spotlight through the incorporation of resin with textiles to create wearables that reflect a hard softness and transform in emphasis. During the day, initial thoughts are formed about a garment- its form, the fabrics, and how it fits to the human body. It is only when darkness falls that the true nature of a piece is revealed. Different areas  are colored and covered, and the transition from light to dark highlights distinct geometries that may not initially be apparent. Through the generous support of Art N’ Glow, Alluminare is an inquiry into materiality, hybrid textiles and viewer experience. \n\n This project was funded [in part] by Carnegie Mellon’s Undergraduate Research Office.",
            "team": "Mariana Alberola / Zain Islam-Hashmi / Stephanie Smid"
        }, 
        {
            "line": "Broqué",
            "description": "A pop culture take on baroque art. You’ve never seen the Kardashians quite like this. We’re broke, but fancy broke. We’re broqué.",
            "team": "Katie Boyle / Arden Wolf"
        }, 

        
        {
            "line": "Beaux",
            "description": "Years ago, when corsets were commonplace amongst western women, they were used to constrain their natural bodys into one uniform shape. Beaux takes the idea of these corsets and flips it on its head by instead allowing the corset to conform and accentuate the shape of the body rather than retrain it. This line aims to empower the woman who wears it by embracing traditional femininity and transforming it to fit the strong modern woman.",
            "team": "Dani Delgado / Rishi Karthikeyan"
        }, {
            "line": "Shibui",
            "description": "Shibui is the Japanese concept of simple forms, pure beauty and serenity, yet a closer look reveals fine textures and intricacies. The line separating masculine and feminine wear is blurred by emphasizing certain aspects of the human body, while concealing others. This visual soundscape softens, bounces and flows with every subtle movement. Each look uses natural materials, complemented by a variation of undulating patterning, bridging between simplicity and complexity.",
            "team": "Ellen Zhu"
        }, 
        {
            "line": "Phantasus",
            "description": " “They are not long, the weeping and the laughter, \n\n  Love and desire and hate: \n\n I think they have no portion in us after \n\n We pass the gate. \n\n  They are not long, the days of wine and roses: \n\n Out of a misty dream \n\n  Our path emerges for awhile, then closes \n\n Within a dream.”  \n\n Inspired by the poem “They are not long” by Ernest Dowson, Phantasus aims to capture the fluidity and strength of dreams and phantasy with the poetic expression of form making. Transform and combine various materials to fully express the movement and curvature of the female body.",
            "team": "Clara Zhao"
        }, 
        {
            "line": "Alumni Line",
            "description": "",
            "team": "Terry Boyd / CeeCee Chang / Sommer Farber / Nancy Geronian / Grace Kao / Jenny Wong / Luther Young / Catherine Zheng / Kevin Zhu"
        }, 
        {
            "line": "Unpoetic Beauty",
            "description": "Unpoetic Beauty is dedicated in providing congruity with the wearer and their garment by challenging the traditional pant suit. The collection focuses on feminine forms to showcase the female figure in a powerful way apart from the suit. The collection draws inspiration from Japanese Samurai's armor and the Victorian time period to create pieces that demonstrate authority, capability and strength.",
            "team": "Christianna Murray"
        }, 
        {
            "line": "Lachesism",
            "description": "LACHESISM, derived from the Dictionary of Obscure Sorrows, explores the desire to shed all constancy, or better put by John Koenig, interrupt the “the stiff prefabricated beam that barely covers the gap between one end of your life and the other.” Intended to arouse discourse and honor victims, individual looks are dedicated to exploring different disasters—some natural, others man-inflicted—and their transformative natures.",
            "team": "Rebecca Kim"
        }, 
        {
            "line": "Slog",
            "description": "Our line is a celebration of the spirit of human labor and bring others together in appreciating the beauty in the mundane. Pieces draw inspiration from the ubiquity and beauty of clothing designed with not aesthetic, but function, in mind. By dissecting and fusing elements from these traditionally functional clothes, we hope to reimagine these pieces and show the beauty in them.",
            "team": "Mimi Jiao / Nina Yoo"
        }, 
        {
            "line": "Urban Nomads",
            "description": "Urban Nomads depicts the process of individual change and growth influenced by their surroundings. The nomad represents an individual with a defined cultural background. Once the individual engages with the unknown environment, the urban, the industrial, and the chaos, they are confused, disturbed, constrained, and overwhelmed. The clash of one’s past with external constituents becomes the topic of experimentation. The line narrates the various stages that one’s identity goes through under exposure to external factors - the richness, absence, clash, and fusion.",
            "team": "Yang Gao / Dingkun D.K. Wang / Yirui Veronica Wang"
        }


    ];